### ISSUE TITLE
Can't verify message from others

### ISSUE THREAD

**Issue by nerdDan** [joule-labs/joule-extension#204]
A reasonable "verify signature" function should look like this:

```
verify(message, signature, pubkey) -> bool
```

However, the current `verifyMessage` looks like this:

```
verifyMessage(signature, message) -> bool
```

This design does not make sense because one can only verify messages signed by oneself, and we actually need to verify messages from others!

**Comment by wbobeirne** [comment]
This is not actually the case, LND message signature verifications work by using the channel graph. You can see the api method here: https://api.lightning.community/#verifymessage

While this may be subject to change, especially as it becomes untenable to keep the whole graph in memory, it's how it works today. What this means is to verify a signature, that node has to be somewhere on your node's graph.

While not ideal for newer users, it does have this interesting side effect of being a good heuristic for real network participants rather than dummy key pairs that are nearly instant to spin up. However, if the API changes in the future to allow non-graph'd nodes to be verified, the method can definitely be amended with an (optional?) third argument of their pubkey.

**Comment by nerdDan** [comment]
@wbobeirne Thank you for pointing out the truth that I failed to notice.

According to the code in LND [1], it firstly recovers the public key from message and signature, then look up the public key in the network. In some scenarios where the expected public key is known, we can verify the signature, no matter the node was in network or not. Thus it would be great if `verifyMessage` could return the public key as LND does.

[1] https://github.com/lightningnetwork/lnd/blob/master/rpcserver.go#L1163

**Comment by nerddan** [comment]
@wbobeirne I made a small module for signing and verifying messages that does not need a connection to Lightning Network.
