### ISSUE TITLE
Multi-Part MPP send support

### ISSUE THREAD

**Issue by Pantamis** [joule-labs/joule-extension#251]
LND now supports the sending of multi-part payment. This was merged in the following PR https://github.com/lightningnetwork/lnd/pull/3967 . It is now in release v0.10.0. You can also have more general infos on how to use it in LND 0.10.0 release notes: https://github.com/lightningnetwork/lnd/releases/tag/v0.10.0-beta .

The payment is automatically split by LND in v0.10.0 until it succeed or until it failed after using the maximum number of parts set by the rpc parameter `--max_parts` in `payinvoice` and other payment commands. `--max_parts`is set to 1 by default (no MPP split). Ideally I would like to set this rpc parameter in Joule options menu else when I send a payment.  Joule would then fill the rpc parameter with the value set in options. 
One drawback is that the introduction of this feature may require the update of LND to version 0.10.0 if you don't detect the LND version. You can also ask users to let the value to 1 if they don't have the required LND version and only fill the rpc parameter when it is bigger than 1. 
I don't know what is the best UX between setting the parameter in settings menu of Joule or when sending a payment. I would rather prefer setting the parameter in the menu.

This feature can wait but as MPP may change a lot the incentives on the size of channels capacity with its adoption it could become necessary and it doesn't look very difficult to add it. Maybe it is already on your roadmap :)

Hope to see this feature soon ! Thank you for the amazing work on this application and on the adoption of Lightning :)

**Comment by wbobeirne** [comment]
Unfortunately this API is only accessible over gRPC via `SendPayment`, but looks like the work isn't backported to `SendPaymentSync` which is what the REST API uses. Joule is limited to the REST API since it runs in the browser, which has no way to communicate over gRPC.

Marking this as blocked, would love to implement it if #8 ever gets done, but it's a huge shift in the way Joule works.

As an aside, I think the best UX is likely one where the user doesn't need to concern themselves with how many paths their payment takes. If we can't find a route with a single payment, try two. If it can't find one with two, try three etc.

**Comment by Pantamis** [comment]
Ok I understand, it would be a big refactoring indeed. Another solution would be to set the default value in LND directly, it would automatically allow MPP in Joule. 

About the UX: LND does that automatically already :) you just need to tell him when it should stop splitting the payment. So I think we agree that it should be a general setting in a menu. 

Setting the default value in LND looks finally much better for UX. It may be a good idea to allow this setting in later LND realeases.

I close the issue as a solution from LND seems much easier and better, thanks again for this amazing app :+1:
