### ISSUE TITLE
Joule no longer available as firefox extension

### ISSUE THREAD

**Issue by ArbenKarb** [joule-labs/joule-extension#260]
### Description of the Feature or Idea

[Your description goes here]
![image](https://user-images.githubusercontent.com/31412198/88321420-6fb47880-cd1f-11ea-82eb-5c14fe337dfd.png)

### Existing Example(s) of Feature

[If another product or app is doing this, please link to it]

**Comment by wbobeirne** [comment]
Argh, looks like it got removed because they weren't able to reproduce the builds locally from the source provided (different checksums.) In the meantime, it can be manually installed from the release assets: https://github.com/joule-labs/joule-extension/releases/tag/v0.5.2. I'll work on getting it restored in the store though.

**Comment by bumi** [comment]
bump, is there anything we can do to get it back up?

**Comment by githorray** [comment]
love bump

**Comment by bumi** [comment]
The main problem is that zip files contain the file modification timestamps and thus the build never fully reproducible. 
The problem of timestamps and reproducible builds is described [here](https://reproducible-builds.org/docs/timestamps/)

To work around this issue we can use the strip-nondeterminism tool ([debian package](https://packages.debian.org/sid/strip-nondeterminism), [git repo](https://salsa.debian.org/reproducible-builds/strip-nondeterminism)) which knows how to normalize typical files like zip files. (by setting a fixed modification timestamp on each file)

Or we update the files manually before zipping as for example described [here](https://medium.com/@pat_wilson/building-deterministic-zip-files-with-built-in-commands-741275116a19). This would need to happen before creating the zip. 
(It seems there is also a not very much used [npm package](https://www.npmjs.com/package/deterministic-zip) that claims to make deterministic zip files)

For now I used the strip-nondeterminism tool, just because using that I did not have to change the build process and could simply update the zip file.

I have created a Dockerfile to run the the build process inside a container and to create the zip package. PR: #268 
This should solve this problem and allow mozilla build and verify the add-on file.


* [Notes on Source Code submission](https://extensionworkshop.com/documentation/publish/source-code-submission) (Checklist and notes on how to provide build instructions)
(It seems that Mozilla also recommends to NOT minify the code and we probably do not need sourcemaps or similar in production. Do you think of anything that we should change in the production build process?)

**Comment by bumi** [comment]
Here is another option which I actually prefer: https://github.com/joule-labs/joule-extension/pull/269
It changes the build process slightly to not create the zip with JS in the webpack build process but using a small bash script.
This has less dependencies and I think it makes it easier to use.

**Comment by lessless** [comment]
thanks for not dropping it on the floor @bumi

**Comment by digisus** [comment]
Hi! Just wanted to try this one out. Clicking on "install for Firefox" from https://lightningjoule.com/ still directs to a defunct github page at https://addons.mozilla.org/en-US/firefox/addon/lightning-joule/. Maybe give some information what is going on instead of a dead-end error message? Thanks.

**Comment by jaxkeiser** [comment]
How do I manually install the addon after I download joule-v0.5.2.zip

**Comment by paboum** [comment]
> Hi! Just wanted to try this one out. Clicking on "install for Firefox" from https://lightningjoule.com/ still directs to a defunct github page at https://addons.mozilla.org/en-US/firefox/addon/lightning-joule/. Maybe give some information what is going on instead of a dead-end error message? Thanks.

Hmm, after 14 months your comment still hasn't been heard. I consider this project dead then, switching to alternatives.

**Comment by ndesanjo** [comment]
It really seems that this project is dead.

**Comment by dylanbathurst** [comment]
Loved this extension back in the day but at this point is there any reason to not use @bumi's Alby instead of Joule?

**Comment by wbobeirne** [comment]
I've updated the README to indicate that the project is no longer being actively developed.
