### ISSUE TITLE
Cannot connect to lnd v0.14.1

### ISSUE THREAD

**Issue by joshuanapoli** [joule-labs/joule-extension#291]
### Description of the Issue
The GetInfo requires macaroon authentication, but joule makes an unauthenticated GetInfo call on the Provide a URL screen.

### Steps to Reproduce
Try to connect a lnd v0.14.1 server

### Description of Your Setup
Chrome 96.0.4664.93
MacOS 12.0.1
lnd v0.14.1

### Console Logs / Screenshots
<img width="459" alt="Screen Shot 2021-12-15 at 10 01 53 PM" src="https://user-images.githubusercontent.com/141162/146300423-9b7c524c-01f1-45ba-92cf-954aaa1f9e32.png">

<img width="692" alt="Screen Shot 2021-12-15 at 10 02 24 PM" src="https://user-images.githubusercontent.com/141162/146300478-e9fd5dcd-3130-4cbc-bcd1-cb1c9a5b417e.png">

**Comment by wbobeirne** [comment]
This check is intentional, it actually is looking for specifically that error: https://github.com/joule-labs/joule-extension/blob/1ba2050ef0dcfacdd6bfedf291acaff39d1baa8a/src/app/modules/node/sagas.ts#L17-L29

As far as I can tell, detection of this error should still work, looks like the message hasn't changed: https://github.com/joule-labs/joule-extension/blob/1ba2050ef0dcfacdd6bfedf291acaff39d1baa8a/src/lnd/utils.ts#L23-L25

The error screenshot shows a different message, so I'm not sure what's going on there, but the API response screenshot looks like everything _should_ be working. Let me know if you can provide any more details.

**Comment by wbobeirne** [comment]
Ah wait never mind, looks like there _was_ a change in 0.14.1, it's returning a 500 status code instead of a 4XX for this now. That's a bug on LND's end unfortunately. I'll open an issue there.

**Comment by wbobeirne** [comment]
Scratch that, looks like it was always a 500, but the important part is that the response object no longer has an `error` key, which Joule was using to distinguish whether or not the response JSON included error information: https://github.com/joule-labs/joule-extension/blob/1ba2050ef0dcfacdd6bfedf291acaff39d1baa8a/src/lnd/http/index.ts#L425-L437. That's... rather unfortunate.

**Comment by joshuanapoli** [comment]
Ah, thanks for looking through this. I agree that it's strange for lnd to give a 500 response to an authentication error. It seems like they need to be more careful to specify their interface contracts for errors.
