### ISSUE TITLE
Feature request: allow to connect to wallets with Bluetooth API

### ISSUE THREAD

**Issue by bitcoinuser** [joule-labs/joule-extension#83]
Hi,

Anton, the developer of https://lightning-wallet.com/ said he is interested in implement bluetooth API.
If he really add it, I think Lightningjoule could allow to comunicate with it.

Interesting article about Bluetooth API: https://medium.com/@urish/start-building-with-web-bluetooth-and-progressive-web-apps-6534835959a6

**Comment by bitcoinuser** [comment]
This too: https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web?hl=en

**Comment by bitcoinuser** [comment]
More interesting links: https://plus.google.com/u/0/communities/108953318610326025178

**Comment by wbobeirne** [comment]
I'm not sure there's much I can do on this front until one of the apps adds this functionality. Is there any form of standard around this?

**Comment by bitcoinuser** [comment]
BLW wallet is starting the work to enable bluetooth: https://github.com/btcontract/lnwallet/commit/de6417bc7247f4425810e49d6c4709d27a722995

**Comment by btcontract** [comment]
Hey there, yeah I think this is an interesting idea and currently I work on implementing Bluetooth basics on BLW side.

How I imagine this would work so far:

1. User enables "Bluetooth payments" option in BLW settings and chooses a device in a list of paired devices (optionally choosing will happen later if needed device is not yet paired).
2. BLW warns user that chosen device will be able to issue automatic payments and remembers it if user proceeds. From now on BLW will only be trying to establish a Bluetooth connection with an approved device. This removes the need for macaroon authorization since network communication is local and also BLW is not password protected so paying can be very straightforward.
3. Once connection is established BLW will be sending stats to Joule (channel details, balance, etc) and listening for deposit/withdraw messages from Joule. I guess the messaging format can be copied from what is currently used to communicate with LND.

Does this look fine so far?

**Comment by wbobeirne** [comment]
That all makes sense, and I think sticking as closely to LND as possible will make for the best developer experience. However, I'm still a little unsure as to how an app on the phone communicates over the device's bluetooth connection. The phone can only connect as one bluetooth "device", so how would I go about specifically communicating with your app on the device? It looks like there're GATT services that provide characteristics to read and write to, but it looks like a typical request -> response architecture is going to be a little tricky.

I have no experience with the Web Bluetooth API so I can't provide a ton of input on how this would look.

**Comment by btcontract** [comment]
> However, I'm still a little unsure as to how an app on the phone communicates over the device's bluetooth connection.

Same here. My plan is, once mobile side is done, to fork Joule and try things out until messaging works. I assume browser extension should at least be able to access Web Bluetooth API (https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API) like websites do?

**Comment by wbobeirne** [comment]
Yep, they most certainly can! That sounds like a good path forward. Don't hesitate to hit me up with any questions you have during that process.
